#!/bin/bash
# Plugin first-run initializer — copies config template to PLUGIN_DATA
# Generated by /package --format plugin

PLUGIN_DATA="${CLAUDE_PLUGIN_DATA}"
PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT}"
CONTEXT_DIR="${PLUGIN_DATA}/context"

if [[ ! -f "${CONTEXT_DIR}/working-directories.md" ]]; then
  mkdir -p "${CONTEXT_DIR}"
  cp "${PLUGIN_ROOT}/templates/working-directories.md" "${CONTEXT_DIR}/working-directories.md"

  cat <<NOTICE >&2
⚙️  First-time setup required for investigate plugin.

Please edit your repo configuration:
  ${CONTEXT_DIR}/working-directories.md

Or paste this prompt into Claude Code to auto-populate:

  Read my git repos in ~/Projects/ and help me populate
  ${CONTEXT_DIR}/working-directories.md.
  For each repo, detect: the GitHub remote (org/repo), main branch name,
  and primary language/framework.

NOTICE
fi

exit 0
